#!/bin/bash

set -e

. $HOME/.zshrc_utils

if [[ $(git diff-tree -r --name-only ORIG_HEAD HEAD) ]]; then
  echo -e "$(yellow [WARN] "package-lock.json changes detected.")"
  while true; do
    read -p "$(echo -e "$(green "[NOTE] Run \"npm install\"? (Y/n) ")")" -n1 answer < /dev/tty
    case $answer in
    Y | y | '')
      npm install
      echo -e "\n$(green "[NOTE] Completed.")"
      exit 0
      ;;
    n)
      echo -e "\n$(red "[WARN] Not Updated.")"
      exit 0
      ;;
    *)
      echo -ne "$(yellow " - Y or n (default \"y\")")\n"
      ;;
    esac
  done
fi
