#!/bin/bash

set -e

source $HOME/.dotfiles/utils/colors.zsh

if [[ $(git --no-pager show -s --format="%s") =~ ^--wip-- ]]; then
  echo -e "$(yellow "[WARN] WIP commit detected.")"
  while true; do
    read -p "$(echo -e "$(green "[NOTE] UNWIP? (Y/n)") ")" -n1 answer </dev/tty
    case $answer in
    Y | y | '')
      git reset HEAD~1 --quiet
      echo -e "\n$(green "[NOTE] Done.")"
      break
      ;;
    n)
      echo -e "\n$(red "[WARN] Canceled.")"
      break
      ;;
    *)
      echo -ne "$(yellow " - Y or n (default \"y\")")\n"
      ;;
    esac
  done
fi
