#!/bin/bash

set -e

source $DOTFILES/utils/colors.zsh

IFS=$'\n'

while read -r message; do
  if [[ $message =~ ^--wip-- ]]; then
    echo -e "$(yellow "[WARN] WIP commit detected. UNWIP by running") $(green "$ gunwip")"
    exit 1
  fi
done <<<"$(git --no-pager show -s --format="%s" @{u}..)"
