#!/usr/bin/env bash

set -euo pipefail

text="${*:-}"

for ((i = 0; i <= 255; i++)); do
  color="$(printf '%03d' "$i")"
  label="${text:-$color}"
  printf '\x1b[48;5;%sm %s \x1b[0m ' "$color" "$label"
  printf '\x1b[38;5;%sm%s\x1b[0m ' "$color" "$label"

  [[ "$i" -lt 16 && $(((i + 1) % 8)) -eq 0 ]] && echo
  [[ "$i" -ge 16 && $(((i - 15) % 6)) -eq 0 ]] && echo
  [[ "$i" -lt 16 && $(((i + 1) % 16)) -eq 0 ]] && echo
  [[ "$i" -ge 16 && $(((i - 15) % 36)) -eq 0 ]] && echo
done
