#!/usr/bin/env bash

_help() {
  cat <<EOF
Usage: color [command] [...arguments]

Available commands:
  help           Print this help
  list           List all colors
  list <text>    List all colors with text
  [0-255]        Print color
  [0-255] <text> Print text with color

Examples:
  color
  color "Hello, World"
  echo \$(color 42 "Hello, World")
  echo "Hello, World" | color 42

EOF
}

_list() {
  _text=$@
  for i in {0..255}; do
    color=$(printf "%03d" $i)
    text=${_text:-$(printf "%03d" $i)}
    printf "\x1b[48;5;${color}m ${text} \x1b[0m "
    printf "\x1b[38;5;${color}m${text}\x1b[0m "

    [ $i -lt 16 ] && [ $((($i + 1) % 8)) -eq 0 ] && echo
    [ $i -ge 16 ] && [ $((($i - 15) % 6)) -eq 0 ] && echo
    [ $i -lt 16 ] && [ $((($i + 1) % 16)) -eq 0 ] && echo
    [ $i -ge 16 ] && [ $((($i - 15) % 36)) -eq 0 ] && echo
  done
}

_read_stdin_or_args() {
  if [ -t 0 ]; then
    echo $@
  else
    cat
  fi
}

_print() {
  color=$1
  text=$(_read_stdin_or_args ${@:2})
  text=${text:-$(printf "%03d" $color)}

  if [ $color -ge 0 ] && [ $color -le 255 ]; then
    printf "\x1b[38;5;${color}m${text}\x1b[0m\n"
  else
    echo "Color must be between 0 and 255"
    exit 1
  fi
}

while [ "$#" -gt 0 ]; do
  case $1 in
  help)
    _help
    exit 0
    ;;

  list)
    _list ${@:2}
    exit 0
    ;;

  prompt)
    _prompt ${@:2}
    exit 0
    ;;

  [0-9]*)
    _print $@
    exit 0
    ;;

  *)
    echo "Unknown option: $1"
    exit 1
    ;;
  esac
done

[ "$#" -eq 0 ] && _list
