#!/usr/bin/env zsh

_version="v0.1.0"

_help() {
  cat <<EOF
Usage: color [options] [...arguments]

Available options:
  -h, --help         Print this help
  -l, --list         List all colors
  -c, --code         Print color by code
  -v, --version      Print version

Examples:
  color --list
  color --list 'Hello, World!'
  color --code 42
  color --code 42 'Hello, World!'
  echo 'Hello, World!' | color --code 42
  echo $(color --code 42 'Hello, World!')
EOF
}

_list() {
  _text=$@
  for i in {0..255}; do
    color=$(printf "%03d" $i)
    text=${_text:-$(printf "%03d" $i)}
    printf "\x1b[48;5;${color}m ${text} \x1b[0m "
    printf "\x1b[38;5;${color}m${text}\x1b[0m "

    [ $i -lt 16 ] && [ $((($i + 1) % 8)) -eq 0 ] && echo
    [ $i -ge 16 ] && [ $((($i - 15) % 6)) -eq 0 ] && echo
    [ $i -lt 16 ] && [ $((($i + 1) % 16)) -eq 0 ] && echo
    [ $i -ge 16 ] && [ $((($i - 15) % 36)) -eq 0 ] && echo
  done
}

_read_stdin_or_args() {
  if [ -t 0 ]; then
    echo $@
  else
    cat
  fi
}

_color() {
  color=$1
  text=$(_read_stdin_or_args ${@:2})
  text=${text:-$(printf "%03d" $color)}

  if [ $color -ge 0 ] && [ $color -le 255 ]; then
    printf "\x1b[38;5;${color}m${text}\x1b[0m\n"
  else
    echo "color must be between 0 and 255"
    exit 1
  fi
}

while getopts "hlt:c:v-:" opt; do
  case $opt in
  l) _list ${@:2} ;;
  c) _color $OPTARG ${@:3} ;;
  v) echo $_version ;;
  -) case $OPTARG in
    list) _list ${@:2} ;;
    code) _color $2 ${@:3} ;;
    version) echo $_version ;;
    *) _help ;;
    esac ;;
  *) _help ;;
  esac
done

if [ $OPTIND -eq 1 ]; then
  _help
fi
